version: "3.7"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./data/https-portal:/var/lib/https-portal
    environment:
      STAGE: production
      DOMAINS: "redmine.2g2t.biz -> http://redmine:3000"
      ACCESS_LOG: stdout
      ERROR_LOG: stdout
      TZ: Asia/Tokyo
  redmine:
    image: redmine:4.1.1-alpine
    restart: always
    volumes: 
      - ./data/redmine/conf/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./data/redmine/files:/usr/src/redmine/files
      - ./data/redmine/plugins:/usr/src/redmine/plugins
    environment: 
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Tokyo
  db:
    image: postgres:13.1-alpine
    restart: always
    volumes: 
      - db-data:/var/lib/postgresql/data
      - ./backup/db:/backup
    environment: 
      POSTGRES_DB: redmine
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Tokyo

volumes: 
  db-data:
